import os
import json
import logging
from pathlib import Path
from langchain_text_splitters import RecursiveCharacterTextSplitter

# Try to get the logger, if not, it will be standard
logger = logging.getLogger(__name__)

# Lazy initialization so the app doesn't crash if imported before pip install
embedder = None
qdrant_client = None
QDRANT_PATH = str(Path(__file__).resolve().parent.parent / "qdrant_data")
COLLECTION_NAME = "feasibility_context"
EMBEDDING_MODEL_NAME = os.getenv("EMBEDDING_MODEL_NAME", "BAAI/bge-small-en-v1.5")
EMBEDDING_LOCAL_FILES_ONLY = os.getenv("EMBEDDING_LOCAL_FILES_ONLY", "").lower() in {"1", "true", "yes"}

def _init_qdrant(load_embedder: bool = True):
    global embedder, qdrant_client
    if qdrant_client is None:
        try:
            from qdrant_client import QdrantClient
            from qdrant_client.models import VectorParams, Distance

            qdrant_client = QdrantClient(path=QDRANT_PATH)

            if not qdrant_client.collection_exists(COLLECTION_NAME):
                qdrant_client.create_collection(
                    collection_name=COLLECTION_NAME,
                    vectors_config=VectorParams(size=384, distance=Distance.COSINE),
                )
        except ImportError as e:
            logger.error(f"Failed to initialize Qdrant/SentenceTransformers. Please install requirements: {e}")
            raise

    if load_embedder and embedder is None:
        try:
            from fastembed import TextEmbedding
            
            # fastembed is MUCH lighter than sentence-transformers and doesn't use torch
            # BAAI/bge-small-en-v1.5 is the default and has size 384 (same as our collection)
            embedder = TextEmbedding(model_name=EMBEDDING_MODEL_NAME)
        except Exception as e:
            logger.error(f"Failed to initialize fastembed: {e}")
            raise


def close_qdrant():
    global qdrant_client
    if qdrant_client is not None:
        try:
            qdrant_client.close()
        except Exception as e:
            logger.warning(f"Failed to close Qdrant client cleanly: {e}")
        finally:
            qdrant_client = None

def embed_conversation_context(conversation_id: str, search_results: str, analysis: str):
    """
    Chunks the search results and the final analysis, embeds them using MiniLM-L6-v2, 
    and inserts them into local Qdrant collection under the given conversation_id.
    """
    try:
        _init_qdrant(load_embedder=True)
    except ImportError:
        logger.warning("Skipping embedding because required dependencies are not installed.")
        return
        
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=500,
        chunk_overlap=50,
        length_function=len
    )
    
    chunks = []
    
    # Chunk the search results
    if search_results:
        # Just simple splitting, source is web research
        sr_chunks = text_splitter.split_text(search_results)
        for chunk in sr_chunks:
            chunks.append({"text": chunk, "source": "web_research"})
            
    # Chunk the analysis (report)
    if analysis:
        try:
            clean_json = analysis.replace("```json", "").replace("```", "").strip()
            data = json.loads(clean_json)
            # Create a string representation to embed
            analysis_text = f"Feasibility Report generated by AI:\n"
            for k, v in data.items():
                if isinstance(v, list):
                    v = " ".join([str(item) for item in v])
                analysis_text += f"{k}: {v}\n"
        except Exception:
            analysis_text = analysis
            
        analysis_chunks = text_splitter.split_text(analysis_text)
        for chunk in analysis_chunks:
            chunks.append({"text": chunk, "source": "feasibility_report"})
            
    if not chunks:
        logger.info("Nothing to embed.")
        print("  [RAG] No text found to embed.")
        return
        
    texts = [c["text"] for c in chunks]
    metadatas = [{"conversation_id": conversation_id, "source": c["source"], "text": c["text"]} for c in chunks]
    
    print(f"\n  [RAG] 🧠 Generating embeddings for {len(chunks)} text chunks (Background Thread)...")

    # Generate vectors and upload to Qdrant
    try:
        from qdrant_client.models import PointStruct
        import uuid
        
        # fastembed returns a generator of vectors
        vectors = list(embedder.embed(texts))
        points = [
            PointStruct(
                id=str(uuid.uuid4()),
                vector=vector.tolist(),
                payload=meta
            )
            for vector, meta in zip(vectors, metadatas)
        ]
        
        qdrant_client.upsert(
            collection_name=COLLECTION_NAME,
            points=points,
            wait=True
        )
        logger.info(f"Successfully embedded {len(points)} chunks for conversation {conversation_id}")
        print(f"  [RAG] ✅ Successfully uploaded {len(points)} chunks to Qdrant for Session {conversation_id}...\n")
    except Exception as e:
        logger.error(f"Error embedding context: {e}")
        print(f"  [RAG] ❌ Failed to embed context: {e}")
